import '@/styles/globals.scss'
import type { AppProps } from 'next/app'
import Layout from '../../components/layout'
import localFont from 'next/font/local'
import Head from 'next/head'

export const josefSans = localFont({
  src: [
    {
      path:'../../public/fonts/Josef/JosefinSans-Medium.ttf',
      weight: '500',
      style:'normal'
    },
    {
      path:'../../public/fonts/Josef/JosefinSans-Light.ttf',
      weight: '300',
      style:'normal'
    }
  ]
})

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Layout>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>
        <Component {...pageProps} />
      </Layout>
    </>
  )
}
